[package]
name = "live-order-book"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48", features = ["full"] }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
futures-util = { version = "0.3.31" }
serde = { version = "1.0.228", features = ["derive"]}
serde_json = { version = "1.0.145"}
ordered-float = {version = "5.1.0"}
